spring:
  datasource:
    url: jdbc:mysql://118.33.81.132:13306/farmin?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1q2w3e4r/
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true